apiVersion: apps/v1
kind: Deployment
metadata:
  name: balloonblooms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: balloonblooms
  template:
    metadata:
      labels:
        app: balloonblooms
    spec:
      containers:
        - name: balloonblooms
          image: kyovens/balloonblooms:main
          ports:
            - containerPort: 3002
          env:
            - name: DB_HOST
              value: "db"
            - name: DB_USER
              value: "root"
            - name: DB_PASS
              value: "root"
            - name: DB_NAME
              value: "web_chat"
      restartPolicy: Always
