apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  type: ClusterIP  # Hanya bisa diakses dari dalam cluster
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
